name: dispatch
on:
  issue_comment:
    types: [created]
permissions:
  contents: read
  issues: write
jobs:
  dispatch:
    runs-on: ubuntu-24.04
    steps:
      - name: Slash Command Dispatch
        # https://github.com/peter-evans/slash-command-dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          permission: none
          commands: |
            ai
